### ISSUE TITLE
WebUI start error: AttributeError: 'AppSettings' object has no attribute '_config'

### ISSUE THREAD

**Issue by owendswang** [rupeshs/fastsdcpu#112]
```
Traceback (most recent call last):
  File "/root/fastsdcpu/src/app.py", line 169, in <module>
    from frontend.webui.ui import start_webui
  File "/root/fastsdcpu/src/frontend/webui/ui.py", line 6, in <module>
    from frontend.webui.models_ui import get_models_ui
  File "/root/fastsdcpu/src/frontend/webui/models_ui.py", line 11, in <module>
    app_settings.settings.lcm_diffusion_setting.openvino_lcm_model_id,
  File "/root/fastsdcpu/src/app_settings.py", line 33, in settings
    return self._config
AttributeError: 'AppSettings' object has no attribute '_config'
```

**Comment by rupeshs** [comment]
Do a fresh install or delete the config/settings.yaml file and try

**Comment by owendswang** [comment]
Sorry I bought an old Nvidia graphic card. I gave up on CPU.
Thanks for the help!
