### ISSUE TITLE
trying to install on android device with Termux

### ISSUE THREAD

**Issue by redflagrul** [rupeshs/fastsdcpu#146]
error: subprocess-exited-with-error
× Preparing metadata (pyproject.toml) did not run successfully. │ exit code: 1
╰─> [26 lines of output] pyproject.toml: line 7: using '[tool.sip.metadata]' to specify the project metadata is deprecated and will be removed in SIP v7.0.0, use '[project]' instead
Traceback (most recent call last): File "/root/fastsdcpu/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/root/fastsdcpu/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main json_out['return_val'] = hook(**hook_input['kwargs'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/root/fastsdcpu/env/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
whl_basename = backend.build_wheel(metadata_directory, config_settings)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-build-env-zxhmuqph/overlay/lib/python3.11/site-packages/sipbuild/api.py", line 46, in build_wheel project = AbstractProject.bootstrap('wheel',
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/tmp/pip-build-env-zxhmuqph/overlay/lib/python3.11/site-packages/sipbuild/abstract_project.py", line 92, in bootstrap project.setup(pyproject, tool, tool_description)
File "/tmp/pip-build-env-zxhmuqph/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 587, in setup self.apply_user_defaults(tool)
File "/tmp/pip-install-v8os1fae/pyqt5_769b1569c0b047649fc14a52abdc4ec0/project.py", line 68, in apply_user_defaults super().apply_user_defaults(tool)
File "/tmp/pip-build-env-zxhmuqph/overlay/lib/python3.11/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults super().apply_user_defaults(tool)
File "/tmp/pip-build-env-zxhmuqph/overlay/lib/python3.11/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
self.builder.apply_user_defaults(tool)
File "/tmp/pip-build-env-zxhmuqph/overlay/lib/python3.11/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults raise PyProjectOptionException('qmake',
sipbuild.pyproject.PyProjectOptionException
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata. ╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by patientx** [comment]
dont use 3.11

**Comment by lustfeind** [comment]
I have the same problem on raspi 4 with Ubuntu 24.04 LTS. I try Python 3.9, 3.10, 3.12 with venv

**Comment by patientx** [comment]
> I have the same problem on raspi 4 with Ubuntu 24.04 LTS. I try Python 3.9, 3.10, 3.12 with venv

First of all this is about android  I don't know about the problem with pi 4. 
And I just reinstalled it in my phone once again. So definetly works.
