### ISSUE TITLE
Error while trying to generate photo first time

### ISSUE THREAD

**Issue by redflagrul** [rupeshs/fastsdcpu#147]
./start-webui.sh 
Starting FastSD CPU please wait...
Found python command
Python version : 3.10.6
Running on Linux platform
OS: Linux-6.5.0-21-generic-x86_64-with-glibc2.35
Processor: x86_64
Using device : cpu
Found 5 LCM models in config/lcm-models.txt
Found 7 stable diffusion models in config/stable-diffusion-models.txt
Found 3 LCM-LoRA models in config/lcm-lora-models.txt
Found 4 OpenVINO LCM models in config/openvino-lcm-models.txt
Starting web UI mode
No lora models found, please add lora models to /home/lts/fastsdcpu/lora_models directory
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Torch datatype : torch.float32
Reshape and compile
{'diffusion_task': 'text_to_image',
 'guidance_scale': 1.0,
 'image_height': 512,
 'image_width': 512,
 'inference_steps': 1,
 'init_image': None,
 'lcm_lora': {'base_model_id': 'Lykon/dreamshaper-8',
              'lcm_lora_id': 'latent-consistency/lcm-lora-sdv1-5'},
 'lcm_model_id': 'stabilityai/sd-turbo',
 'lora': {'enabled': False,
          'fuse': True,
          'models_dir': '/home/lts/fastsdcpu/lora_models',
          'path': '',
          'weight': 0.5},
 'negative_prompt': '',
 'number_of_images': 1,
 'openvino_lcm_model_id': 'rupeshs/sd-turbo-openvino',
 'prompt': 'cat',
 'seed': 123123,
 'strength': 0.6,
 'use_lcm_lora': False,
 'use_offline_model': False,
 'use_openvino': True,
 'use_safety_checker': False,
 'use_seed': False,
 'use_tiny_auto_encoder': False}
***** Init Text to image (OpenVINO) - rupeshs/sd-turbo-openvino *****
Traceback (most recent call last):
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status
    response.raise_for_status()
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/rupeshs/sd-turbo-openvino/resolve/main/model_index.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1232, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1608, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 303, in hf_raise_for_status
    raise HfHubHTTPError(str(e), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/rupeshs/sd-turbo-openvino/resolve/main/model_index.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 370, in load_config
    config_file = hf_hub_download(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1349, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/gradio/blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/gradio/utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
  File "/home/lts/fastsdcpu/src/frontend/webui/text_to_image_ui.py", line 54, in generate_text_to_image
    images = future.result()
  File "/home/lts/miniconda3/envs/sdcpu/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/home/lts/miniconda3/envs/sdcpu/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/lts/miniconda3/envs/sdcpu/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/lts/fastsdcpu/src/context.py", line 50, in generate_text_to_image
    self.lcm_text_to_image.init(
  File "/home/lts/fastsdcpu/src/backend/lcm_text_to_image.py", line 132, in init
    self.pipeline = get_ov_text_to_image_pipeline(
  File "/home/lts/fastsdcpu/src/backend/openvino/pipelines.py", line 47, in get_ov_text_to_image_pipeline
    pipeline = OVStableDiffusionPipeline.from_pretrained(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/optimum/modeling_base.py", line 344, in from_pretrained
    config = cls._load_config(
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/optimum/intel/openvino/modeling_diffusion.py", line 506, in _load_config
    return cls.load_config(config_name_or_path, **kwargs)
  File "/home/lts/fastsdcpu/env/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 397, in load_config
    raise EnvironmentError(
OSError: rupeshs/sd-turbo-openvino does not appear to have a file named model_index.json.

**Comment by redflagrul** [comment]
I think I know what the problem is huggingface is down

**Comment by q5325150** [comment]
> I think I know what the problem is huggingface is down我想我知道问题出在哪里 huggingface is down

Did you solve this problem?I also downloaded the model and placed it in the cache directory of Hugging Face, but it didn't take effect.
