### ISSUE TITLE
I tried to use FastSdCpu offline but got this error:

### ISSUE THREAD

**Issue by JohnClaw** [rupeshs/fastsdcpu#15]
Traceback (most recent call last):
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\util\connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\Николай\AppData\Local\Programs\Python\Python310\lib\socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connectionpool.py", line 492, in _make_request
    raise new_e
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x000001B32D243B20>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\fzo\fastsdcpu\env\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/deinferno/LCM_Dreamshaper_v7-openvino/revision/main (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B32D243B20>: Failed to resolve 'huggingface.co' ([Errno 11001] getaddrinfo failed)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\fzo\fastsdcpu\main.py", line 67, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\fzo\fastsdcpu\main.py", line 266, in generate_image
    self.pipeline = OVLatentConsistencyModelPipeline.from_pretrained(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\optimum\modeling_base.py", line 372, in from_pretrained
    return from_pretrained_method(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\optimum\intel\openvino\modeling_diffusion.py", line 228, in _from_pretrained
    model_id = snapshot_download(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\huggingface_hub\_snapshot_download.py", line 189, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\huggingface_hub\hf_api.py", line 1888, in repo_info
    return method(
  File "C:\fzo\fastsdcpu\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\huggingface_hub\hf_api.py", line 1697, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "C:\fzo\fastsdcpu\env\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /api/models/deinferno/LCM_Dreamshaper_v7-openvino/revision/main (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000001B32D243B20>: Failed to resolve \'huggingface.co\' ([Errno 11001] getaddrinfo failed)"))'), '(Request ID: 6c1bb8d5-20ad-4898-bf4b-91caeca962f2)')

Could you make it work offline, please?

**Comment by rupeshs** [comment]
Internet connection is required, offline not supported currently.

**Comment by JohnClaw** [comment]
> Internet connection is required, offline is not supported currently.

Very sad news.

**Comment by rupeshs** [comment]
Model downloading needs internet.

**Comment by JohnClaw** [comment]
> Model downloading needs internet.

I mean an offline use when the model is already downloaded. Is it possible?

**Comment by rupeshs** [comment]
Okay, it can be achieved, I'll check

**Comment by JohnClaw** [comment]
> Okay, it can be achieved, I'll check

Let God bless your kind heart. Thank you.

**Comment by rupeshs** [comment]
@JohnClaw  Added offline model support, available in the master branch.
![image](https://github.com/rupeshs/fastsdcpu/assets/3255994/d6a61063-5fa7-4a2a-9b36-b901909d415b)

**Comment by JohnClaw** [comment]
> Added offline model support, available in the master branch.

It works. Thank you very much.
