### ISSUE TITLE
android (termux) solution seems to be broken

### ISSUE THREAD

**Issue by patientx** [rupeshs/fastsdcpu#201]
Haven't tried for a few months now, decided to refresh if any problems occur and indeed they did occur. After installing as usual, first start :  

'Settings not found creating default settings                  Running on Linux platform                                     OS: Linux-4.14.186-g7c18952d3c68-aarch64-with-glibc2.35       Processor: aarch64                                            Using device : cpu                                            Found 8 LCM models in config/lcm-models.txt                   Found 7 stable diffusion models in config/stable-diffusion-models.txt                                                       Found 4 LCM-LoRA models in config/lcm-lora-models.txt
Found 7 OpenVINO LCM models in config/openvino-lcm-models.txt Traceback (most recent call last):
  File "/root/fastsdcpu/src/app.py", line 278, in <module>
    from frontend.webui.ui import start_webui
  File "/root/fastsdcpu/src/frontend/webui/ui.py", line 10, in <module>
    from frontend.webui.controlnet_ui import get_controlnet_ui
  File "/root/fastsdcpu/src/frontend/webui/controlnet_ui.py", line 6, in <module>
    from backend.annotators.image_control_factory import ImageControlFactory
  File "/root/fastsdcpu/src/backend/annotators/image_control_factory.py", line 1, in <module>
    from backend.annotators.canny_control import CannyControl
  File "/root/fastsdcpu/src/backend/annotators/canny_control.py", line 3, in <module>
    from cv2 import Canny
  File "/root/fastsdcpu/env/lib/python3.10/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/root/fastsdcpu/env/lib/python3.10/site-packages/cv2/__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory'

What do you think, is it fixable or we lost android all together ?

Edit ::: solved it by adding those lib files in your "new" guide.

**Comment by hubono** [comment]
Hi
Can u point us to those lib files and how to install them and the new guide please

**Comment by patientx** [comment]
> Hi Can u point us to those lib files and how to install them and the new guide please

I meant the steps he wrote on the main readme, which adds installing ffmpeg 

apt-get install ffmpeg (or apt install ffmpeg)
