### ISSUE TITLE
Can't start it.

### ISSUE THREAD

**Issue by hubkn** [rupeshs/fastsdcpu#206]
When i try opening start.bat it just opens and then closes and nouthing happens.

**Comment by KintCark** [comment]
Maybe it's cause he is currently updating it

**Comment by hubkn** [comment]
How do you know he's updating if so when will it be done.

**Comment by KintCark** [comment]
He said he was gonna update I don't know when he is dropping it:)

**Comment by rupeshs** [comment]
@KintCark No my updates will not impact already-done software. I will be working on a different git branch.

@hubkn Please follow this tutorial https://youtu.be/331QGLNY4sU

**Comment by hubkn** [comment]
Traceback (most recent call last):
  File "C:\Users\Angus\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\\src\app.py", line 5, in <module>
    from backend.controlnet import controlnet_settings_from_dict
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\src\backend\controlnet.py", line 3, in <module>
    from diffusers import ControlNetModel
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\diffusers\utils\__init__.py", line 21, in <module>
    from .constants import (
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\diffusers\utils\constants.py", line 21, in <module>
    from .import_utils import ENV_VARS_TRUE_VALUES, is_peft_available, is_transformers_available
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\diffusers\utils\import_utils.py", line 27, in <module>
    from huggingface_hub.utils import is_jinja_available  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\huggingface_hub\utils\__init__.py", line 41, in <module>
    from ._errors import (
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\huggingface_hub\utils\_errors.py", line 6, in <module>
    from ._fixes import JSONDecodeError
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\huggingface_hub\utils\_fixes.py", line 20, in <module>
    import yaml
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\yaml\__init__.py", line 8, in <module>
    from .loader import *
  File "C:\Users\cool\Downloads\fastsdcpu-1.0.0-beta.32\fastsdcpu-1.0.0-beta.32\env\Lib\site-packages\yaml\loader.py", line 5, in <module>
    from .scanner import *
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1069, in get_code
  File "<frozen importlib._bootstrap_external>", line 729, in _compile_bytecode

Getting this error when running webui.bat

**Comment by rupeshs** [comment]
@hubkn Which model are you using? Are you using control net?

**Comment by hubkn** [comment]
Yea i followed the tutorial, like what im saying is i cant start the web ui i just get that error i listed above in the tutorial it just shows once he/she installed it they open up web ui and then generate image it automatically on the yt vid installs the models then starts generating the image i hadn't installed any other things by my self i was just following yt vid?

**Comment by hubkn** [comment]
Should i manually put models in folder if so which models would you recommend and what folder btw thank you very much for your help it's really appreciated.

**Comment by rupeshs** [comment]
@hubkn Are you using Windows 11?

**Comment by hubkn** [comment]
Yes.

**Comment by rupeshs** [comment]
@hubkn Please do a fresh install.

**Comment by hubkn** [comment]
Of windows 11 or fasts sd cpu

**Comment by rupeshs** [comment]
@hubkn FastSD CPU

**Comment by hubkn** [comment]
Done ain't working btw using python version 3.11.6

**Comment by rupeshs** [comment]
@hubkn  FastSD CPU will work AMD CPUs (Users already reported)

**Comment by rupeshs** [comment]
@hubkn  FastSD CPU supported on 64 bit OS.
