### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Fortress937** [rupeshs/fastsdcpu#233]
When i run 'install-bat' it show me this error:

ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\urllib3\response.py", line 437, in _error_catcher
    yield
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\urllib3\response.py", line 526, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 465, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1278, in recv_into
    return self.read(nbytes, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1134, in read
    return self._sslobj.read(len, buffer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\cli\req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\commands\install.py", line 400, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 92, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\resolvelib\structs.py", line 151, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 297, in __init__
    super().__init__(
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 162, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\operations\prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\operations\prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
                 ^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\operations\prepare.py", line 166, in unpack_url
    file = get_http_url(
           ^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\operations\prepare.py", line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\network\download.py", line 147, in __call__
    for chunk in chunks:
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\urllib3\response.py", line 621, in stream
    data = self.read(amt=amt, decode_content=decode_content)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\urllib3\response.py", line 559, in read
    with self._error_catcher():
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\User\Downloads\fastsdcpu-1.0.0-beta.35\fastsdcpu-1.0.0-beta.35\env\Lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Comment by Fortress937** [comment]
nevermind it was fixed by reinstalling.
