### ISSUE TITLE
start-webserver.sh fail with pydantic schema-for-unknown-type

### ISSUE THREAD

**Issue by keiser1080** [rupeshs/fastsdcpu#253]
Hi,

I tryied the colab and it failed with pydantic error.
So i create a new environment on a linux headless server:
- pyenv install 3.11.9
- pyenv local 3.11.9
- clone repo
- cd fastsdcpu
- pyenv local 3.11.9
-  chmod +x install.sh
- install.sh --disable-gui 
- ./start-webui.sh

and same i get the same error 

```
51 $ ./start-webui.sh
Starting FastSD CPU please wait...
Found python command
Python version : 3.11.9
Settings not found creating default settings
Running on Linux platform
OS: Linux-6.1.0-21-amd64-x86_64-with-glibc2.36
Processor: 
Using device : cpu
Found 8 LCM models in config/lcm-models.txt
Found 7 stable diffusion models in config/stable-diffusion-models.txt
Found 4 LCM-LoRA models in config/lcm-lora-models.txt
Found 9 OpenVINO LCM models in config/openvino-lcm-models.txt
/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
  return register_model(fn_wrapper)
Starting web UI mode
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
No lora models found, please add lora models to /home/myuser/project/fastsdcpu/lora_models directory
/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/gradio/components/dropdown.py:179: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  or set allow_custom_value=True.
  warnings.warn(
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
IMPORTANT: You are using gradio version 4.23.0, however version 4.29.0 is available, please upgrade.
--------
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_utils.py", line 77, in collapse_excgroups
  |     yield
  |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 186, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    |     result = await app(  # type: ignore[func-returns-value]
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    |     return await self.app(scope, receive, send)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    |     await super().__call__(scope, receive, send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    |     raise exc
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    |     await self.app(scope, receive, _send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
    |     with collapse_excgroups():
    |   File "/home/myuser/.pyenv/versions/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    |     raise exc
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 187, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/gradio/route_utils.py", line 675, in dispatch
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 163, in call_next
    |     raise app_exc
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 149, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    |     await self.middleware_stack(scope, receive, send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    |     await route.handle(scope, receive, send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    |     await self.app(scope, receive, send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    |     raise exc
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    |     await app(scope, receive, sender)
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    |     response = await f(request)
    |                ^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    |     solved_result = await solve_dependencies(
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    |     ) = await request_body_to_args(  # body_params checked above
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 813, in request_body_to_args
    |     fields_to_extract = get_cached_model_fields(first_field.type_)
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 657, in get_cached_model_fields
    |     return get_model_fields(model)
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    |     return [
    |            ^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    |     ModelField(field_info=field_info, name=name)
    |   File "<string>", line 6, in __init__
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 110, in __post_init__
    |     self._type_adapter: TypeAdapter[Any] = TypeAdapter(
    |                                            ^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/type_adapter.py", line 241, in __init__
    |     core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/type_adapter.py", line 156, in _get_schema
    |     schema = gen.generate_schema(type_)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    |     schema = self._generate_schema(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    |     schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 691, in _generate_schema_inner
    |     return self._annotated_schema(obj)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1524, in _annotated_schema
    |     schema = self._apply_annotations(source_type, annotations)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1592, in _apply_annotations
    |     schema = get_inner_schema(source_type)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    |     schema = self._handler(__source_type)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1682, in new_handler
    |     schema = metadata_get_schema(source, get_inner_schema)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1678, in <lambda>
    |     lambda source, handler: handler(source)
    |                             ^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    |     schema = self._handler(__source_type)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1573, in inner_handler
    |     schema = self._generate_schema(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    |     schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    |     return self.match_type(obj)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 794, in match_type
    |     return self._match_generic_type(obj, origin)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 818, in _match_generic_type
    |     return self._union_schema(obj)
    |            ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1006, in _union_schema
    |     choices.append(self.generate_schema(arg))
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    |     schema = self._generate_schema(obj)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    |     schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
    |                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    |     return self.match_type(obj)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 798, in match_type
    |     return self._unknown_type_schema(obj)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    |     raise PydanticSchemaGenerationError(
    | pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
    | 
    | If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.
    | 
    | For further information visit https://errors.pydantic.dev/2.4/u/schema-for-unknown-type
    +------------------------------------

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 185, in __call__
    with collapse_excgroups():
  File "/home/myuser/.pyenv/versions/3.11.9/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_utils.py", line 83, in collapse_excgroups
    raise exc
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 187, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/gradio/route_utils.py", line 675, in dispatch
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 163, in call_next
    raise app_exc
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/base.py", line 149, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 639, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 813, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 657, in get_cached_model_fields
    return get_model_fields(model)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 284, in get_model_fields
    return [
           ^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 285, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/fastapi/_compat.py", line 110, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
                                           ^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/type_adapter.py", line 241, in __init__
    core_schema = _get_schema(type, config_wrapper, parent_depth=_parent_depth + 1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/type_adapter.py", line 156, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 691, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1524, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1592, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1682, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1678, in <lambda>
    lambda source, handler: handler(source)
                            ^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1573, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 794, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 818, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1006, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 452, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 711, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 798, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myuser/project/fastsdcpu/env/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 366, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.4/u/schema-for-unknown-type
^CKeyboard interruption in main thread... closing server.

```

**Comment by keiser1080** [comment]
seems to work using the lastest gradio.

`
$ source env/bin/activate
$ pip install -U gradio
$ pip freeze | grep gradio
gradio==4.44.0
gradio_client==1.3.0`
