### ISSUE TITLE
[gradio]UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence

### ISSUE THREAD

**Issue by liuguoping1024** [rupeshs/fastsdcpu#260]
**Describe the bug:**

Traceback (most recent call last):
  File "E:\fastsdcpu-1.0.0-beta.50\\src\app.py", line 10, in <module>
    from frontend.webui.image_variations_ui import generate_image_variations
  File "E:\fastsdcpu-1.0.0-beta.50\src\frontend\webui\image_variations_ui.py", line 2, in <module>
    import gradio as gr
  File "E:\fastsdcpu-1.0.0-beta.50\env\Lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "E:\fastsdcpu-1.0.0-beta.50\env\Lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "E:\fastsdcpu-1.0.0-beta.50\env\Lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "E:\fastsdcpu-1.0.0-beta.50\env\Lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "E:\fastsdcpu-1.0.0-beta.50\env\Lib\site-packages\gradio\components\multimodal_textbox.py", line 34, in <module>
    class MultimodalTextbox(FormComponent):
  File "E:\fastsdcpu-1.0.0-beta.50\env\Lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "E:\fastsdcpu-1.0.0-beta.50\env\Lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 2074: illegal multibyte sequence

**Related bug:**
https://github.com/gradio-app/gradio/issues/7856

**Suggestion:**
I think a new version of gradio should be used.

**Comment by rupeshs** [comment]
@liuguoping1024 thanks for reporting it

**Comment by rupeshs** [comment]
@liuguoping1024 Please use the latest version of FastSD.
