### ISSUE TITLE
`KeyError: ''`

### ISSUE THREAD

**Issue by SilianZ** [rupeshs/fastsdcpu#275]
```
Traceback (most recent call last):
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\anyio\_backends\_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\env\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "D:\Codespaces\fastsdcpu\src\frontend\webui\lora_models_ui.py", line 57, in on_click_load_lora
    settings.lora.path = lora_models_map[lora_name]
                         ~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: ''

```

**Comment by rupeshs** [comment]
@SilianZ  If you are using lora model please follow this tutorial https://www.youtube.com/watch?app=desktop&v=N_LUxd6G2nk

**Comment by asstormcoming** [comment]
> @SilianZ If you are using lora model please follow this tutorial https://www.youtube.com/watch?app=desktop&v=N_LUxd6G2nk

I followed the tutorial, but I'm having the same issue when I click the Load selected LoRA button

**Comment by rupeshs** [comment]
Thanks for reporting @SilianZ  @asstormcoming  It was due to gradio version issue, fix is coming soon. Thank you for using FastSdcpu

**Comment by rupeshs** [comment]
@SilianZ  @asstormcoming Fixed in the latest release https://github.com/rupeshs/fastsdcpu/releases/tag/v1.0.0-beta.100
