### ISSUE TITLE
 Error no file named model_index.json found in directory 

### ISSUE THREAD

**Issue by myrfy001** [rupeshs/fastsdcpu#85]
I have use the following to download offline  model
```
git lfs install
git clone https://huggingface.co/latent-consistency/lcm-lora-sdv1-5
```

and my config files as :

settings.yaml:
```
lcm_diffusion_setting:
  diffusion_task: text_to_image
  guidance_scale: 1.0
  image_height: 512
  image_width: 512
  inference_steps: 1
  init_image: null
  lcm_lora:
    base_model_id: runwayml/stable-diffusion-v1-5
    lcm_lora_id: D:\study\lcm-lora-sdv1-5
  lcm_model_id: D:\study\lcm-lora-sdv1-5
  negative_prompt: ''
  number_of_images: 1
  openvino_lcm_model_id: rupeshs/LCM-dreamshaper-v7-openvino
  prompt: ''
  seed: -1
  strength: 0.6
  use_lcm_lora: false
  use_offline_model: true
  use_openvino: false
  use_safety_checker: false
  use_seed: false
  use_tiny_auto_encoder: false
results_path: D:\study\fastsdcpu\results

```

lcm-lora-models.txt:
```
latent-consistency/lcm-lora-sdv1-5
latent-consistency/lcm-lora-sdxl
latent-consistency/lcm-lora-ssd-1b
D:\study\lcm-lora-sdv1-5
```

stable-diffusion-models.txt:
```
Lykon/dreamshaper-8
Fictiverse/Stable_Diffusion_PaperCut_Model
stabilityai/stable-diffusion-xl-base-1.0
runwayml/stable-diffusion-v1-5
segmind/SSD-1B
stablediffusionapi/anything-v5
prompthero/openjourney-v4
D:\study\lcm-lora-sdv1-5
```

error message:
```
***** Init LCM Model pipeline - D:\study\lcm-lora-sdv1-5 *****
Traceback (most recent call last):
  File "D:\study\fastsdcpu\src\frontend\gui\image_generator_worker.py", line 29, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\study\fastsdcpu\src\frontend\gui\app_window.py", line 553, in generate_image
    images = self.context.generate_text_to_image(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\study\fastsdcpu\src\context.py", line 31, in generate_text_to_image
    self.lcm_text_to_image.init(
  File "D:\study\fastsdcpu\src\backend\lcm_text_to_image.py", line 147, in init
    self.pipeline = get_lcm_model_pipeline(
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\study\fastsdcpu\src\backend\pipelines\lcm.py", line 69, in get_lcm_model_pipeline
    pipeline = DiffusionPipeline.from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Miniconda3\envs\py311\Lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1099, in from_pretrained
    config_dict = cls.load_config(cached_folder)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Miniconda3\envs\py311\Lib\site-packages\diffusers\configuration_utils.py", line 364, in load_config
    raise EnvironmentError(
OSError: Error no file named model_index.json found in directory D:\study\lcm-lora-sdv1-5.
```

**Comment by rupeshs** [comment]
@myrfy001  Are you able to solve this? Could you please use the latest release

**Comment by khanumballz** [comment]
Same problem here. No idea what's going on.

Using latest release
